site_name: Optuna-ExternM Documentation
site_author: Tony Hallam
docs_dir: docs
site_dir: site
theme:
  name: material
  language: "en"
  features:
    - navigations.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
  palette:
    primary: green
  icon:
    repo: fontawesome/brands/github
  custom_dir: docs/overrides
use_directory_urls: false
repo_url: https://github.com/trhallam/optuna-externm
repo_name: trhallam/optuna-externm
edit_uri: edit/main/docs

copyright: "Tony Hallam"

markdown_extensions:
  - admonition
  - footnotes
  - tables
  - codehilite:
      guess_lang: false
  - toc:
      permalink: false
  # - pymdownx.snippets:
  #     auto_append: ["docs/hyperlinks.md"]
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: true
      auto_title: true
  - pymdownx.superfences
  - pymdownx.smartsymbols
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - simple:
      # build_docs_dir: docs_build
  - autorefs
  # - mkdocs-jupyter:
  #     execute: true
  #     kernel_name: python3
  #     include_source: true
  #     include: ["examples/example*.py"]
  #     ignore: ["*.ipynb"]
  - mkdocstrings:
      default_handler: python
      watch:
        - optuna-externm
        - scripts
  - include-markdown
  - gen-files:
      scripts:
        - scripts/gen_configs.py


nav:
  - "Home":
    - "About": index.md
    - "Contributing": "contrib.md"
    - "Contact": "contact.md"
    - "Issue Tracker": https://github.com/trhallam/optuna-externm/issues

  - "Sensitivity Analysis":
    - "Introduction": sa/intro.md
    - "OVAT": sa/ovat.md
    - "Sobol": sa/sobol.md

  - "Optimisation":
    - "Introduction": opt/intro.md
    - "Cma-Es": opt/cmaes.md
    - "Lex-De": opt/lexde.md

  - "User Guide":
    - "Optuna-ExternM Framework": "ug/framework.md"
    # - "Examples"
      # - "Sim2x imp": examples/example_sim2imp.py
      # # - "Sim2X rg":
      # - "Wavelets": examples/example_wavelets.py
      # # - "PSF":
      # # - 
      # - "Full Sim2seis": examples/example_t1a.py
    - "CLI": cli/cli.md

  - "API":
    - "Core": api/core.md
    # - "rg": api/rg.md
    # - "Wavelets": api/wavelets.md
    # - "seis": api/seis.md

  - "Optuna-HM":
    - "About": "ophm/about.md"
    - "Tutorial": "ophm/tutorial.md"
    - "API":
      - "Handlers": "ophm/api_handlers.md"
      - "Metrics": "ophm/api_metrics.md"
