name: Publish docs via GitHub Pages

on: [push, pull_request]

env:
  PACKAGE: optuna-externm

jobs:

  mkdocs_build_test_deploy:

    name: build mkdocs
    runs-on: ubuntu-latest

    steps:

      - name: Checkout optuna-externm
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: trhallam/optuna-externm
          token: ${{ secrets.GH_PRIVATE_TOKEN }}

      # required to use caching because it depends on requirements.txt
      - name: create requirements optuna-externm
        run: |
          python -m pip install --upgrade pip
          pip install pip_tools
          pip-compile setup.cfg --extra docs

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install package and deps optuna-externm
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install .

      - name: Checkout optuna-hm
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: trhallam/optuna-hm
          token: ${{ secrets.GH_PRIVATE_TOKEN }}

      # required to use caching because it depends on requirements.txt
      - name: create requirements optuna-hm
        run: |
          mv setup.cfg setup.cfg.bu
          grep -v optuna-externm setup.cfg.bu > setup.cfg
          pip-compile setup.cfg

      - name: Install package and deps optuna-hm
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install .

      - name: Checkout main
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: build docs
        run: mkdocs build -f mkdocs.yml

      - name: deploy mkdocs
        if: success() && github.event_name == 'push' && github.ref_name == 'main'
        run: mkdocs gh-deploy -f mkdocs.yml

  docs_badge:
    name: create docs badges
    if: always() && github.ref_name == 'main'
    needs: [mkdocs_build_test_deploy]
    runs-on: ubuntu-latest

    steps:
    - name: passed?
      if: needs.mkdocs_build_test_deploy.result == 'success'
      run: |
        echo "BADGE_COLOUR=green" >> $GITHUB_ENV
        echo "BADGE_MSG=pass" >> $GITHUB_ENV

    - name: failed?
      if: needs.mkdocs_build_test_deploy.result == 'failure'
      run: |
        echo "BADGE_COLOUR=RED" >> $GITHUB_ENV
        echo "BADGE_MSG=fail" >> $GITHUB_ENV

    - name: create test badges
      if:
      uses: schneegans/dynamic-badges-action@v1.1.0
      with:
        auth: ${{ secrets.GIST_TOKEN }}
        gistID: 0da415ee1bf30b0fc37a2fc4ddafbdee
        filename: ${{ env.PACKAGE }}_docs.json
        label: Docs
        namedLogo: Read the Docs
        logoColor: white
        message: ${{ env.BADGE_MSG }}
        color: ${{ env.BADGE_COLOUR }}
